# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fdc1fc1c2de713c8b8f9696c28b07754383f1567d01e10a40931fd66538367324845d078b92f1382bb87587573a0885f3b15ca3efed19ec27674ca2abe651ab7

test:
  secret_key_base: 75f1ff5057ac5a04a198d6581353052383583bb2d03e6bc13c0b05f7323beef7160454f2580d00115b0c3a037f2cbda3356161fded256f5f46813136112b8850

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
